baseURL = "https://brain.wayanjimmy.xyz/"
languageCode = "id-id"
title = "Wayan Jimmy's Brain"
theme = "cortex"


[params]
email = "jimmyeatcrab@gmail.com"
footer = "Icon by Freepik. Built with ♥ with Org-mode and Hugo."

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xHTML = false

  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "github"
    tabWidth = 4

[outputFormats]
  [outputFormats.Embed]
    baseName = "embed"
    isPlainText = false
    isHTML = true
    mediaType = "text/html"
    permalinkable = true
  [outputFormats.Page]
    baseName = "page"
    isPlainText = false
    isHTML = true
    mediaType = "text/html"
    permalinkable = true

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML", "EMBED", "PAGE"]

