#+title: Kishore Mahbubani ASEAN Deserves a Nobel Peace Prize
#+hugo_base_dir: ~/JimboyLabs/resources/braindump
#+hugo_section: ./notes

- link :: [[https://youtu.be/AKNVomZuKoo][Kishore Mahbubani: ASEAN Deserves a Nobel Peace Prize | Endgame S2E01]]

* Meritokrasi vs Plutokrasi
China vs Amerika adalah pertandingan [[file:20201206111407-meritokrasi.org][Meritokrasi]] dengan [[file:20201206111510-plutokrasi.org][Plutokrasi]].

Untuk dapat menjadi seorang yang bekerja di pemerintah China, terjadi kompetisi yang sangat ketat hampir sama dengan kompetisi untuk bisa berkuliah di Harvard.

Sedangkan di Amerika, keputusan Politik dipengaruhi oleh orang-orang yang kaya, membangun rezim pajak yang hanya menguntung hanya 1% bagian dari seluruh penduduk yang merupakan orang kaya tersebut.

Hal ini sempat diperingatkan oleh seorang filsuf Jown Rawls, [[file:20201206112558-money_to_determine_politics.org][Money to determine politics]].

Baik Trump atau Biden keduanya belum bisa dikatakan sebagai /wake up call/ untuk permasalahan Amerika, masalah yang dialami adalah /Sistemik/ maka memerlukan solusi yang juga /Sistemik/, bukan sekadar perubahan individual.

* China tidak mencetuskan perang selama 40 tahun
Kishore menjelaskan bahwa strategi Amerika dalam menghadapi China seperti tanpa perhitungan, Disamping itu China tidak mencetuskan perang selama 40 tahun, sama sekali tidak menembakan peluru, disisi lain Amerika saat kepemimpinan Obama melepaskan 26.000 bom ke 7 negara berbeda.

Dana yang dihabiskan untuk perang setelah tragedi 911 pun menghabiskan sekitar 5triliun dollar, bagaimana kalau uang itu sebaiknya digunakan untuk membantu 50% kelas bawah amerika, maka setiap warga negara akan menerima masing masing 30.000 dollar. Mengapa membuang uang untuk perang? padahal rakyat sendiri menderita.
