#+title: Menjalani Quarter Life Crisis
#+hugo_base_dir: ~/JimboyLabs/resources/blog.wayanjimmy.xyz
#+hugo_section: ./blog
#+hugo_publishdate: 2020-12-05

Tulisan ini dibuat untuk berpartisipasi di tweet oleh [[https://twitter.com/kelimuttu/status/1306535724561252354][Kiki]], yang mengajak untuk berbagi pengalaman menghadap Quarter Life Crisis (QLC), sambil menyelam minum air, aku tulis jadi blog post aja deh

Menurutku salah satu akar masalah dari QLC adalah diriku yang berubah, mengalami [[file:20201204205806-merantau.org::Perubahan Mindset][perubahan]] yang cukup besar dari sisi cara berpikir (/mindset/) atau pandangan menjalani hidup. Hal ini membuatku seperti gak ngenalin lagi diriku yang sebenarnya. Aku ga tau lagi apa hal yang aku suka, apa yang membuatku marah, ataupun sedih (jangan ikutan sedih ya wqwq)

Jadi untuk bisa menghadapi situasi ini, mari mencari solusinya, yaitu belajar mengenali lagi diri sendiri. Ini beberapa hal yang aku sedang lakukan:

1. Rajin nulis /daily journal/ [fn:1]. Apa yang dirasakan saat ini aku coba tulis, seperti bicara sama diri sendiri, selain belajar nulis aku juga jadi bisa melihat alur pikiran dari waktu ke waktu, apakah masih sama dengan yang dulu atau sudah berubah.

2. Menulis retro setiap hari sebelum tidur [fn:2]. Emang sulit banget sih setiap hari, tapi aku berusaha, walaupun masih sering bolong. Format retroku berupa 2 pertanyaan berikut.

   * Apa yang kamu pelajari?
   * Apa hal yang mengesankan hari ini?

   Setiap hari pasti ada hal baru dipelajari, dan belajar bersyukur tentang hari itu.

3. Kunjungi lagi tulisan lama. Kalau lagi bosen kadang aku baca-baca lagi tulisan sendiri secara acak. Mungkin aja nemu hal yang menarik.

4. Banyak coba hal yang baru. Dengan coba hal yang baru aku bisa meningkatkan probabilitas menemukan hobi yang baru. Aku bersyukur banget temenku ngenalin aku main /Cruise Board/ [fn:3], menurutku itu versi beginner banget-nya /Skate board/. Rasanya asik banget!!! Ngerasa telat deh baru belajar di-umur yang sudah tidak muda lagi wqwq

5. Teruslah bertanya kepada diri sendiri. Ini adalah metode yang baru aku coba, sejauh ini aku suka dengan cara ini, setiap ada pertanyaan yang tiba-tiba muncul dikepala, coba untuk tulis dan cari jawabannya.

6. /Never accept status quo/, tulisan ini aku baca di tagline linked-in seorang yang menginterview aku dalam sebuah wawancara kerja, aku ingat betul sampai sekarang. Setiap baca kalimat ini serasa diingatkan terus untuk jangan pasrah menerima keadaan saat ini, lakukan sesuatu untuk perbaiki dan temukan caraku sendiri untuk memperbaiki-nya.

Akhir kata aku sendiri belum bisa bilang diriku keluar dari QLC, terlalu optimis juga ya kalau bilang QLC seolah-olah umurku 100 tahun. Tapi aku sedang berusaha, semangat juga buat kalian yang sedang menghadapi.

Kamu tidak sendiri, terimalah keadaan ini & /Find your *true self*/ [fn:4].

* Catatan Kaki

[fn:1] [[https://nesslabs.com/interstitial-journaling][Interstitial journaling: combining notes, to-do and time tracking]]
[fn:2] [[https://medium.com/@nikitavoloboev/day-evaluations-5706f31c9c5e#.m4lw1eo32][Day Evaluations]]
[fn:3] [[https://notebook.wayanjimmy.xyz/longboard][Cruise board]]
[fn:4] [[https://open.spotify.com/episode/68I7IwIoHSVxDARErcmpdS][True Self]]
