#+title: Cerita cinta dengan Macos

* Berkenalan dengan Vim
Judulnya tentang Macos, kok malah bahas Vim? eh bentar dulu, jadi aku awal kenalan sama vim, sekitaran tahun 2015 dikenalin sama Darma Kotama. Kotama waktu itu lagi training di kantornya yang bos-nya orang jepang dan Vim adalah salah satu skill yang di transfer saat training di kantornya.

Tapi si Kotama udah ngerasa nih kalau vim ini bikin dia produktif, dan akupun dikenalin lewat video call. Singkatnya aku juga mulai belajar setelah itu, seminggu penuh pakai vim. Adaptasinya emang susah dan berbulan-bulan, aku ga inget pasti, intinya akupun jatuh cinta dengan Vim.

Kenapa? karena kita bisa dengan cepat navigasi ke bagian kodingan manapun, manipulasi, hanya dengan kibord. Lupakan mousemu. Ada 2 buku yang aku saranin kalau mau belajar Vim
+ [[https://pragprog.com/titles/dnvim2/practical-vim-second-edition/][Practical Vim]]
+ [[https://pragprog.com/titles/bhtmux2/tmux-2/][Tmux 2: Productive Mouse-Free Development]]

Tmux juga aku saranin buat dipelajarin, karena itu semacam katalis buat vim, bikin vim workflowmu lebih lengkap ketika berinteraksi dengan beberapa sesi terminal.

* Produktivitas ala Spotlight
Pengguna Macos pastinya pernah pakai Spotlight
